### PR TITLE
docs: updates communication details in README.md

### PR DESCRIPTION
**Pull request by jpower432**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation (change which affects the documentation site) (**README.md**)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [ ] My code follows the code style of this project.
- [X] Documentation for my change is up to date?
- [ ] My PR meets testing requirements.
- [ ] All new and existing tests passed.
- [X] All commits are signed-off.

## Summary

Updates Community meeting details in README.md

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by jpower432** [comment]
This is in draft pending the addition of the notes link only. Other changes can be reviewed in the meantime.

**Review by AleJo2995 — APPROVED** [review]
LGTM. I have updated the convert tool as the previous link didn't work

**Review by mrgadgil — APPROVED** [review]
LGTM.

**Comment by AleJo2995** [comment]
@degenaro Do you know why is this happening in the end? I'm applying the fix temporarily because we need to merge this details before tomorrow's call, but I haven't found a reason either. And what I see is weirder is that locally I'm not being able to reproduce it

**Comment by jpower432** [comment]
Thanks for adding the fix @AleJo2995. CI is passing now, is this good to merge?

**Pull request merged**
