### PR TITLE
refactor: update trestle documentation webpage's Demo section to be in sync with the demo repo

### PR DESCRIPTION
**Pull request by Ma1h01**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary
1. The demo repo was recently updated. The trestle documentation webpage should also be updated.
## Key links:

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by AleJo2995** [comment]
@Ma1h01 Please check the corresponding checks on section _**Quality assurance (all should be covered).**_

**Comment by Ma1h01** [comment]
@AleJo2995  Quality Assurance sections are now checked

**Review by AleJo2995 — APPROVED** [review]
LGTM

**Comment by AleJo2995** [comment]
@Ma1h01 update the branch and squash and merge when you can. The other problem related with the code of conduct will be resolved in other branch. Thanks

**Pull request merged**
