### PR TITLE
fix: default value for optional string params should be None

### PR DESCRIPTION
**Pull request by gvauter**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [X] My code follows the code style of this project.
- [X] Documentation for my change is up to date?
- [X] My PR meets testing requirements.
- [X] All new and existing tests passed.
- [X] All commits are signed-off.

## Summary
Fixes [Issue #1562](https://github.com/oscal-compass/compliance-trestle/issues/1562)

Optional string parameters should have a default value of `None` instead of empty string.

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by butler54** [comment]
Might be worth having a talk with @degenaro on whether we can avoid manual edits. I'm assuming the code generation side has not been updated yet.

**Review by degenaro — APPROVED** [review]
LGTM, however Vikas, Alejandro & Jenn are better at the markdown related trestle artifacts support. I recommend getting at least one of them to additionally approve.

**Review by jpower432 — APPROVED** [review]
LGTM

**Review by AleJo2995 — APPROVED** [review]
LGTM. Remember to update the branch and squash and merge before merging! Thanks

**Comment by AleJo2995** [comment]
@butler54 just wondering what do you mean by manual edits? I don't remember seeing specifically repository.py class to be generated out of the OSCAL objects during the code generation

**Pull request merged**
