### PR TITLE
fix: correct security vulnerability

### PR DESCRIPTION
**Pull request by AleJo2995**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by AleJo2995** [comment]
I already tested out the change in the repo that is using trestle and the vulnerability has been resolved successfully

image

**Review by mrgadgil — COMMENTED** [review]
This looks like a major version upgrade. Can you look at the change log to verify nothing breaks for us

**Comment by AleJo2995** [comment]
To me there's not actually something to be worried about in terms of any breaking changes so far. Here's the link for the 3.1.0 change coming from 3.0.1 version we had https://github.com/pallets/jinja/releases/tag/3.1.0. I don't see anything in particular to be worried about. for 3.1.3 they fix the vuln and that's pretty much it

**Review by mrgadgil — APPROVED** [review]
LGTM. Thank you for verifying.

**Pull request merged**
