### PR TITLE
fix(profile-resolve): handle unspecified aggregate parameters

### LINKED ISSUE #1706: `trestle author profile-resolve` does not properly handle unset aggregate parameters
## Describe the bug

When some or all of the components of an aggregate parameter have not been set in a profile, `trestle author profile-resolve` uses empty list notation (`[ , , ]`) in the `prose` of the resulting statement, as shown below:

```json
"id": "ma-2.2_smt",
"name": "statement",
"parts": [
  {
    "id": "ma-2.2_smt.a",
    "name": "item",
    "props": [
      {
        "name": "label",
        "value": "(a)"
      }
    ],
    "prose": "Schedule, conduct, and document maintenance, repair, and replacement actions for the system using [, , ] ; and"
  },
```

## To Reproduce

1. Import control `ma-2.2` from NIST 800-53.
2. Do not set the parameters.
3. Run `trestle author profile-resolve`.

## Expected behavior

Populate the statement with the user-specified prefix (e.g. "organization-defined") and the labels for the unset parameters.

## Environment

- OS: macOS
- Python version: 3.12.2
- Installed packages: `trestle` 3.4.0

### PR DESCRIPTION
**Pull request by michaeldavie-amzn**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [ ] My PR meets testing requirements.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

Uses the aggregate parameter label if no sub-parameters have values specified.

## Key links:

- Fixes #1706
- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Review by jpower432 — APPROVED** [review]
LGTM. I was able to test this and verify the change worked successfully.

**Comment by jpower432** [comment]
@AleJo2995 Wanted to ensure you got a chance to review before merging since this is related to #1596

**Review by AleJo2995 — APPROVED** [review]
LGTM

**Comment by AleJo2995** [comment]
@michaeldavie-amzn apologies for the delay on the response. This is good to go now. Thanks a lot.

**Pull request merged**
