### PR TITLE
docs: adds ROADMAP.md with high level roadmap description

### LINKED ISSUE #1480: Trestle Roadmap
Here is the roadmap for trestle for next few months. This list will be kept updated.

- Update trestle to latest OSCAL version v1.1.1
  - New feature requests have been frozen and a new release will be made with additional features in develop.
  - Any bug fixes to current version will continue
  - Current version will be supported for at least 90 days after release of new trestle version with latest OSCAL 
- OSCAL support for CRM in Component Definition
  - CRM would be added to future release of OSCAL
  - Trestle will add support once it is released
- OSCAL support for Mapping model
  - Working with NIST for mapping model support in OSCAL
  - Trestle will add mapping model functionality once it is released
- POAM authoring
  - High level POAM authoring design for FedRAMP is ready
  - Trestle will add support based on prioritization of this requirement after move to OSCAL v1.1.1

### LINKED ISSUE #1622: Create a ROADMAP.md file
## Issue description / feature objectives

We need an easier way to share the project `ROADMAP` with the community. It currently resides in an issue which can be difficult to find.

## Caveats / Assumptions

- It is very easy for static `ROADMAP.md` to get out of date. The `ROADMAP.md` should point to the dynamic roadmap in a GitHub project

## Completion Criteria

- Translate #1480 into Epics and add to the GitHub Project
- Add a `ROADMAP.md` containing how the ROADMAP is defined, where to go to get updates on the roadmap (meetings), and how to add to the roadmap.
- Close #1480

### PR DESCRIPTION
**Pull request by jpower432**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [ ] My code follows the code style of this project.
- [X] Documentation for my change is up to date?
- [ ] My PR meets testing requirements.
- [ ] All new and existing tests passed.
- [X] All commits are signed-off.

## Summary

Adds `ROADMAP.md`
Closes #1480 
Closes #1622 

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by jpower432** [comment]
If desired in this PR or perhaps a follow on PR, we could added how things are scheduled and approximate timelines.

I would propose:
1. Release ready-to-go features monthly, documented through milestones.
2. For high-level items that need to be broken down and executed, schedule to a "Cycle" iteration that lasts 12 weeks. This give us time to get community input, break them down, and add them to a monthly release. The goal here would be to given an overall priority or order to high level items with the flexibility to adjust them if needed.

Any thoughts or feedback?

**Comment by butler54** [comment]
> 2\. For high-level items that need to be broken down and executed, schedule to a "Cycle" iteration that lasts 12 weeks. This give us time to get community input, break them down, and add them to a monthly release. The goal here would be to given an overall priority or order to high level items with the flexibility to adjust them if needed.

I think this makes sense to me.  As i'm pseudo on the outside (moonlighting on this project when I get some cycles) I think we should be explicit with respect to encouraging contributers to submit issues in advance of PRs. e.g.

"Contributors are encouraged to get feedback early by submitting issues to new work they would like to complete and getting feedback.."

**Review by degenaro — APPROVED** [review]

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Review by mrgadgil — APPROVED** [review]
LGTM. thank you for updating

**Review by AleJo2995 — COMMENTED** [review]
Inside note/question to self... I know this is a Roadmap not mentioning any particular details on any structured/well-formed release strategy, but as I was reading I wondered, does it worth mentioning somewhere how bugs/issues are going to be treated in the meantime? Maybe just slightly mentioning it somewhere should be enough, I wouldn´t want to leave any loophole there.

**Comment by jpower432** [comment]
> Inside note/question to self... I know this is a Roadmap not mentioning any particular details on any structured/well-formed release strategy, but as I was reading I wondered, does it worth mentioning somewhere how bugs/issues are going to be treated in the meantime? Maybe just slightly mentioning it somewhere should be enough, I wouldn´t want to leave any loophole for letting people trying to figure out how bugs are treated.

@AleJo2995 Want to make sure I understand. There is a line that says bugs and security fixes will be release on demand, but is your comment referring to the fact that we have not settled on a branching approach and that on-demand releases may include new features, resulting in a minor version milestone bump?

**Comment by AleJo2995** [comment]
@jpower432 my apologies, I must have skiped the 'on demand' basis part on text, that's exactly what I meant to see reflected. Approved.

**Review by AleJo2995 — APPROVED** [review]

**Pull request merged**
