### PR TITLE
fix(docs): add cookie consent popup

### PR DESCRIPTION
**Pull request by butler54**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

Adding a cookie consent popup using inbuilt `mkdocs-material` flags

Closes: #1676 

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Review by degenaro — APPROVED** [review]
LGTM, module fixing the formatting issue there seems to be.

**Review by jpower432 — APPROVED** [review]
LGTM

**Comment by butler54** [comment]
Will fix the build bug and get it released.

**Comment by butler54** [comment]
Do not merge until #1659 is merged.

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Pull request merged**
