### PR TITLE
fix: correct missing script

### PR DESCRIPTION
**Pull request by butler54**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary
Fixes that the required script was missing. We all miss this in review (whoops)

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Review by jpower432 — APPROVED** [review]
LGTM

**Review by jpower432 — CHANGES_REQUESTED** [review]
@butler54 I did a re-review here. I did some additional local testing of the new script and got an error relation to `os.exit()`. Did you mean `sys.exit()`? 

Side note - I am wonder if having a dry-run option for PR changes to docs would be beneficial to catch this these of errors in CI. Maybe a follow-on type of action?

**Review by jpower432 — APPROVED** [review]
LGTM

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Pull request merged**
