### PR TITLE
fix: abstract python version in pipelines

### PR DESCRIPTION
**Pull request by butler54**
- **fix: spelling**
- **fix: Update codeql pipeline**
- **feat: Abstract python versions**
- **feat: Abstract python versions from the pipeline**

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

This abstracts out the python version from the pipeline and updates all versions of the github actions.

It makes the assumption that minimum and maxmimum versions are enough for testing.
As a result two admin tasks are required:

1. Defining repository variables `PYTHON_MIN` and `PYTHON_MAX` (see image in comment)
2. Updating build pipeline to reflect the changes.

This partially addresses: #1608 and closes: #1559 when completed 

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit'
- Ensure CI is currently passing
- Is this a merge to `develop` from any branch except `main` and `ghpages`

### CODE REVIEW

**Comment by butler54** [comment]
image

The following variables are required to make this work.

**Review by vikas-agarwal76 — APPROVED** [review]
Added PYTHON_MAX, and PYTHON_MIN variables.

**Comment by butler54** [comment]
@vikas-agarwal76  - the required tests will need to be changed based on this PR

**Review by jpower432 — APPROVED** [review]
LGTM - I can update the required tests

**Pull request merged**
