### PR TITLE
fix: correct logo redirection for PyPi page

### LINKED ISSUE #1628: Compliance Trestle Logo is breaking on the PyPi page
## Describe the bug

Quite recently there has been a new release and while reviewing PyPi page, the logo is not appearing properly in the webpage

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Screenshots / Logs.

image

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

### PR DESCRIPTION
**Pull request by AleJo2995**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

Closes #1628 

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Review by jpower432 — COMMENTED** [review]
@AleJo2995 Would it be better to point to `main` to get the image? I don't expect the image to change anytime soon, but wondering if we would only want to see a change to the image in PyPi after it was merged to main.

**Comment by AleJo2995** [comment]
@jpower432 I think it is the same for both branches but you're right, I think makes more sense to point to main instead. The only purpose for this is to load the image in PyPi yes.

**Review by butler54 — APPROVED** [review]
LGTM

**Review by jpower432 — APPROVED** [review]
LGTM

**Pull request merged**
