### PR TITLE
feat: adds `x-trestle-add-props` to the YAML header in SSP markdown

### LINKED ISSUE #1524: Support adding generic properties during SSP authoring
## Issue description / feature objectives

When a custom YAML header is used with ssp generate, it would be helpful to be able to specify extra properties at the implemented requirement and statement level.

An example use case for this would be adding `implementation-status` and `control-origination` properties to meet FedRAMP OSCAL SSP requirements without having to edit the JSON.

## Caveats / Assumptions
- This would support generic properties and there would be no special handling per framework (i.e. this will not map to specific OSCAL fields)
- The `x-trestle-add-props` logic for profile authoring could be leveraged

## Completion Criteria

- Similar to the profile markdown, add a comment section that can be uncommented to process custom properties.
- This must support adding namespace information for each property or adding applicable properties under a higher level namespace key in a nested fashion.
- This must support adding properties to implemented requirements and statements (not at the by-component level)

### PR DESCRIPTION
**Pull request by jpower432**
## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [ ] My code follows the code style of this project.
- [X] Documentation for my change is up to date?
- [X] My PR meets testing requirements.
- [X] All new and existing tests passed.
- [X] All commits are signed-off.

## Summary

Reuses logic from profile markdown generation with `x-trestle-add-props` in SSP markdown.

Closes #1524 

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

### CODE REVIEW

**Comment by jpower432** [comment]
@vikas-agarwal76 @AleJo2995 Planning to keep this in draft until features are accepted and will rework as needed. Wanted to share the approach earlier though.

**Comment by jpower432** [comment]
@vikas-agarwal76 Manually validated with version changes merged in. Marking as ready for review.

**Comment by degenaro** [comment]
@jpower432 Perhaps you could update `docs/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring.md` accordingly to help document to users the enhancement provided in this PR? And/or elsewhere if (more) appropriate?

**Review by degenaro — APPROVED** [review]
LGTM

**Review by AleJo2995 — APPROVED** [review]
LGTM

**Comment by AleJo2995** [comment]
@jpower432 I have approved this PR. Let's see if @vikas-agarwal76 has any itch but seems straightforward enough to squash and merge as soon as Vikas approves

**Comment by degenaro** [comment]
Only 1 approver is required for squash & merge. No reason to delay, IMO.

**Comment by jpower432** [comment]
Per the discussion at today's issue review, this is ready for merge.

**Pull request merged**
